name: halopet_beta
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  get: ^4.6.1
  cupertino_icons: ^1.0.2
  firebase_core: 1.10.6
  firebase_auth: 3.3.4
  cloud_firestore: 3.1.5
  flutter: 
    sdk: flutter
  dropdown_search: ^2.0.1
  get_storage: ^2.0.3
  intl: ^0.17.0

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

