part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  // static const LOGIN = _Paths.LOGIN;
  static const HOMEPAGE = _Paths.HOMEPAGE;
  static const SIGNUP = _Paths.SIGNUP;
  static const ADD_PETSHOP = _Paths.ADD_PETSHOP;
  static const PAYMENT = _Paths.PAYMENT;
  static const PETSHOP_DETAIL = _Paths.PETSHOP_DETAIL;
  static const CREATE_ORDER = _Paths.CREATE_ORDER;
  static const DOCTOR_REGISTRATION = _Paths.DOCTOR_REGISTRATION;
  static const PROFILE = _Paths.PROFILE;
  static const ORDER = _Paths.ORDER;
  static const HISTORY = _Paths.HISTORY;
  static const PET_HOTEL_ORDER = _Paths.PET_HOTEL_ORDER;
  static const ORDER_DETAIL = _Paths.ORDER_DETAIL;
  static const HISTORY_DETAIL = _Paths.HISTORY_DETAIL;
  static const ADMIN_HOME = _Paths.ADMIN_HOME;
  static const ADMIN_LIST_USERS = _Paths.ADMIN_LIST_USERS;
  static const SELLER_HOME = _Paths.SELLER_HOME;
  static const SELLER_HISTORY = _Paths.SELLER_HISTORY;
  static const SERVICE_FORM = _Paths.SERVICE_FORM;
  static const SELLER_ORDER_DETAIL = _Paths.SELLER_ORDER_DETAIL;
  static const ADMIN_PETSHOP_APPROVAL = _Paths.ADMIN_PETSHOP_APPROVAL;
  static const WELCOME_PAGE = _Paths.WELCOME_PAGE;
  static const CATEGORY_PAGE = _Paths.CATEGORY_PAGE;
  static const SERVICE_LIST = _Paths.SERVICE_LIST;
  static const FAVORITE = _Paths.FAVORITE;
  static const RATING = _Paths.RATING;
  static const PET_LIST = _Paths.PET_LIST;
  static const PET_FORM = _Paths.PET_FORM;
  static const CHOOSE_PET = _Paths.CHOOSE_PET;
  static const PACKAGE_FORM = _Paths.PACKAGE_FORM;
  static const PETSHOP_LIST = _Paths.PETSHOP_LIST;
  static const INFORMATION = _Paths.INFORMATION;
  static const PACKAGE_LIST = _Paths.PACKAGE_LIST;
  static const TOPUP = _Paths.TOPUP;
  static const DELIVERY_LIST = _Paths.DELIVERY;
  static const NOTIFICATION_LIST = _Paths.NOTIFICATION_LIST;
  static const NOTIFICATION_DETAIL = _Paths.NOTIFICATION_DETAIL;
  static const SESSION_LIST = _Paths.SESSION_LIST;
  static const CHOOSE_SESSION = _Paths.CHOOSE_SESSION;
  static const SESSION_DETAIL = _Paths.SESSION_DETAIL;
  static const CHOOSE_DATE = _Paths.CHOOSE_DATE;
}

abstract class _Paths {
  _Paths._();
  // static const LOGIN = '/login';
  static const HOMEPAGE = '/homepage';
  static const SIGNUP = '/signup';
  static const ADD_PETSHOP = '/add-petshop';
  static const PAYMENT = '/payment';
  static const PETSHOP_DETAIL = '/petshop-detail';
  static const CREATE_ORDER = '/create-order';
  static const DOCTOR_REGISTRATION = '/doctor-registration';
  static const PROFILE = '/profile';
  static const ORDER = '/order';
  static const HISTORY = '/history';
  static const PET_HOTEL_ORDER = '/pet-hotel-order';
  static const ORDER_DETAIL = '/order-detail';
  static const HISTORY_DETAIL = '/history-detail';
  static const ADMIN_HOME = '/admin-home';
  static const ADMIN_LIST_USERS = '/admin-list-users';
  static const SELLER_HOME = '/seller-home';
  static const SELLER_HISTORY = '/seller-history';
  static const SERVICE_FORM = '/service-form';
  static const SELLER_ORDER_DETAIL = '/seller-order-detail';
  static const ADMIN_PETSHOP_APPROVAL = '/admin-petshop-approval';
  static const WELCOME_PAGE = '/welcome-page';
  static const CATEGORY_PAGE = '/category-page';
  static const SERVICE_LIST = '/service-list';
  static const FAVORITE = '/favorite';
  static const RATING = '/rating';
  static const PET_LIST = '/pet-list';
  static const PET_FORM = '/pet-form';
  static const CHOOSE_PET = '/choose-pet';
  static const PACKAGE_FORM = '/package-form';
  static const PETSHOP_LIST = '/petshop-list';
  static const INFORMATION = '/information';
  static const PACKAGE_LIST = '/package-list';
  static const TOPUP = '/topup';
  static const DELIVERY = '/delivery-list';
  static const NOTIFICATION_LIST = '/notification-list';
  static const NOTIFICATION_DETAIL = '/notification-detail';
  static const SESSION_LIST = '/session-list';
  static const CHOOSE_SESSION = '/choose-session';
  static const SESSION_DETAIL = '/session-detail';
  static const CHOOSE_DATE = '/choose-date';
}
